# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2


references:

  defaults: &defaults
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.2

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

  dependencies_key: &dependencies_key
    v1-dependencies-{{ checksum "requirements.txt"}}

  restore_dependencies: &restore_dependencies
    restore_cache:
      keys:
        - *dependencies_key


jobs:

  checkout_code:
    <<: *defaults
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/

  install_dependencies:
    <<: *defaults
    steps:  
      - *restore_repo
      - *restore_dependencies
      - run: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
      - save_cache:
          key: dependencies_key
          paths:
            - ~/dependencies

  test:
    <<: *defaults
    steps:
      - *restore_repo
      - *restore_dependencies
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            nosetests -v --with-coverage --cover-package satsearch

  deploy:
    <<: *defaults
    steps:
      - *restore_repo
      - *restore_dependencies
      - run:
          name: Deploy
          command: |
            . venv/bin/activate
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            pip install twine
            python setup.py sdist
            VERSION=`awk -F\' '{print $2,$4}' satsearch/version.py`
            git tag $VERSION
            git push origin $VERSION
            twine upload --username "${PYPI_USER}" --password "${PYPI_PASS}" dist/*


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - test:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
